import { describe, it, expect, beforeEach } from 'vitest'
import './prisma-mock'
import { resetMockDb, seedMockSkill, getMockSkills, getMockFiles } from './prisma-mock'

import { POST as propose } from '@/app/api/skills/[id]/ai/propose/route'
import { POST as apply } from '@/app/api/skills/[id]/ai/apply/route'

function makeRequest(url: string, body: unknown) {
  return new Request(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  }) as unknown as import('next/server').NextRequest
}

const validSkillData = {
  title: 'Test Skill',
  slug: 'test-skill',
  summary: 'A test skill for validation',
  inputs: 'Query string',
  outputs: 'Cleaned result',
  steps: ['Parse input', 'Process data', 'Return output'],
  risks: 'May timeout',
  triggers: ['deduplicate news', 'clean data', 'parse logs'],
  guardrails: {
    allowed_tools: ['Read'],
    disable_model_invocation: false,
    user_invocable: true,
    stop_conditions: ['Stop when empty'],
    escalation: 'ASK_HUMAN',
  },
  tests: [{ name: 'basic', input: 'hello', expected_output: 'world' }],
  _tags: ['NLP'],
}

describe('AI API', () => {
  beforeEach(() => {
    resetMockDb()
    // Set CLAUDE_BIN to fake claude for tests
    process.env.CLAUDE_BIN = `node ${process.cwd()}/tests/fixtures/fake-claude.mjs`
  })

  describe('POST /api/skills/:id/ai/propose', () => {
    it('should return a changeSet from fake claude', async () => {
      const skill = seedMockSkill(validSkillData)
      const req = makeRequest(
        `http://localhost:3000/api/skills/${skill.id}/ai/propose`,
        { action: 'update-skill', instruction: 'improve the summary' }
      )
      const res = await propose(req, { params: Promise.resolve({ id: String(skill.id) }) })

      expect(res.status).toBe(200)
      const data = await res.json()
      expect(data.changeSet).toBeDefined()
      expect(data.changeSet.skillPatch).toBeDefined()
      expect(data.changeSet.fileOps).toBeDefined()
      expect(data.pathPreview).toBeDefined()
    })

    it('should return 404 for non-existent skill', async () => {
      const req = makeRequest(
        'http://localhost:3000/api/skills/999/ai/propose',
        { action: 'update-skill' }
      )
      const res = await propose(req, { params: Promise.resolve({ id: '999' }) })
      expect(res.status).toBe(404)
    })

    it('should return 400 for missing action', async () => {
      const skill = seedMockSkill(validSkillData)
      const req = makeRequest(
        `http://localhost:3000/api/skills/${skill.id}/ai/propose`,
        {}
      )
      const res = await propose(req, { params: Promise.resolve({ id: String(skill.id) }) })
      expect(res.status).toBe(400)
    })
  })

  describe('POST /api/skills/:id/ai/apply', () => {
    it('should apply changeSet and update DB', async () => {
      const skill = seedMockSkill(validSkillData)
      const changeSet = {
        skillPatch: { summary: 'Updated by AI' },
        fileOps: [
          {
            op: 'upsert',
            path: 'references/rules.md',
            mime: 'text/markdown',
            content_text: '# Rules\n\nGenerated by AI.',
          },
        ],
      }

      const req = makeRequest(
        `http://localhost:3000/api/skills/${skill.id}/ai/apply`,
        { changeSet }
      )
      const res = await apply(req, { params: Promise.resolve({ id: String(skill.id) }) })

      expect(res.status).toBe(200)
      const data = await res.json()
      expect(data.skill).toBeDefined()

      // Verify DB was updated
      const updatedSkill = getMockSkills().get(skill.id as number)
      expect(updatedSkill?.summary).toBe('Updated by AI')

      // Verify file was created
      const files = Array.from(getMockFiles().values())
      const rulesFile = files.find((f) => f.path === 'references/rules.md')
      expect(rulesFile).toBeDefined()
      expect(rulesFile?.contentText).toBe('# Rules\n\nGenerated by AI.')
    })

    it('should reject changeSet with illegal path', async () => {
      const skill = seedMockSkill(validSkillData)
      const changeSet = {
        skillPatch: {},
        fileOps: [
          { op: 'upsert', path: '../etc/passwd', content_text: 'hacked' },
        ],
      }

      const req = makeRequest(
        `http://localhost:3000/api/skills/${skill.id}/ai/apply`,
        { changeSet }
      )
      const res = await apply(req, { params: Promise.resolve({ id: String(skill.id) }) })

      expect(res.status).toBe(400)
      const data = await res.json()
      expect(data.errors).toBeDefined()
      expect(data.errors.length).toBeGreaterThan(0)
    })

    it('should reject changeSet targeting SKILL.md', async () => {
      const skill = seedMockSkill(validSkillData)
      const changeSet = {
        skillPatch: {},
        fileOps: [
          { op: 'upsert', path: 'SKILL.md', content_text: 'overwrite' },
        ],
      }

      const req = makeRequest(
        `http://localhost:3000/api/skills/${skill.id}/ai/apply`,
        { changeSet }
      )
      const res = await apply(req, { params: Promise.resolve({ id: String(skill.id) }) })

      expect(res.status).toBe(400)
      const data = await res.json()
      expect(data.errors.some((e: string) => e.includes('SKILL.md'))).toBe(true)
    })

    it('should return 404 for non-existent skill', async () => {
      const req = makeRequest(
        'http://localhost:3000/api/skills/999/ai/apply',
        { changeSet: { skillPatch: {}, fileOps: [] } }
      )
      const res = await apply(req, { params: Promise.resolve({ id: '999' }) })
      expect(res.status).toBe(404)
    })

    it('should handle delete fileOp', async () => {
      const skill = seedMockSkill(validSkillData)

      // First create a file via apply
      const createReq = makeRequest(
        `http://localhost:3000/api/skills/${skill.id}/ai/apply`,
        {
          changeSet: {
            skillPatch: {},
            fileOps: [
              { op: 'upsert', path: 'references/temp.md', mime: 'text/markdown', content_text: 'temp' },
            ],
          },
        }
      )
      await apply(createReq, { params: Promise.resolve({ id: String(skill.id) }) })

      // Verify file exists
      let files = Array.from(getMockFiles().values())
      expect(files.find((f) => f.path === 'references/temp.md')).toBeDefined()

      // Now delete it
      const deleteReq = makeRequest(
        `http://localhost:3000/api/skills/${skill.id}/ai/apply`,
        {
          changeSet: {
            skillPatch: {},
            fileOps: [{ op: 'delete', path: 'references/temp.md' }],
          },
        }
      )
      const res = await apply(deleteReq, { params: Promise.resolve({ id: String(skill.id) }) })
      expect(res.status).toBe(200)

      // Verify file was deleted
      files = Array.from(getMockFiles().values())
      expect(files.find((f) => f.path === 'references/temp.md')).toBeUndefined()
    })
  })
})
