#!/usr/bin/env node
/**
 * fake-claude.mjs - 模拟 Claude CLI headless 输出
 * 用于 CI 测试，不依赖真实 claude 二进制
 *
 * 输出符合 Claude headless JSON 结构（含 structured_output 字段）
 * structured_output 返回一个 changeSet：修改 summary、添加 references/rules.md
 */

// 输出固定的 changeSet
const output = {
  type: 'result',
  subtype: 'success',
  result: 'Here is the proposed change set.',
  structured_output: {
    skillPatch: {
      summary: 'AI-improved summary for better clarity and precision',
    },
    fileOps: [
      {
        op: 'upsert',
        path: 'references/rules.md',
        mime: 'text/markdown',
        content_text: '# Rules\n\nGenerated by AI.\n\n- Rule 1: Validate inputs\n- Rule 2: Check outputs',
      },
    ],
    notes: 'Improved summary and added references/rules.md',
  },
  usage: {
    input_tokens: 150,
    output_tokens: 80,
  },
}

process.stdout.write(JSON.stringify(output))
process.exit(0)
